name: 'App Deploy'

on:
  push:
    branches:
    - main

  pull_request:
    types:
    - opened
    - synchronize
    - reopened
    - closed
    branches:
    - main

jobs:
  call_app_deploy:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    uses: justinyoo/acsauth/.github/workflows/app-deploy.yaml@main
    with:
      job_name: 'Deploy Static Web App'
      app_location: 'src'
      api_location: 'api'
      output_location: ''
    secrets:
      gh_token: ${{ secrets.GITHUB_TOKEN }}
      aswa_token: '${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}'

  call_pr_close:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    uses: justinyoo/acsauth/.github/workflows/pr-close.yaml@main
    with:
      job_name: 'Close Pull Request'
    secrets:
      aswa_token: '${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}'
