name: 'PR Close'

on:
  workflow_call:
    inputs:
      job_name:
        type: string
        required: true
    secrets:
      aswa_token:
        required: true

jobs:
  close_pull_request_job:
    name: ${{ inputs.job_name }}

    runs-on: ubuntu-latest

    steps:
      - name: Close Pull Request
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_DEV }}
          action: "close"
